#!/usr/bin/env python3
"""The direction table, printed as `packages/geom/src/directions.ts`.

1,024 directions, a turn split evenly; direction 0 points along +x and 256 along +y (the screen's
down). Each is (cos, sin) scaled by 2^14 and rounded half away from zero.

Only the first octant (0..128) is computed with `math.cos` / `math.sin`; the rest is filled by the
circle's symmetries, so the table is *exactly* symmetric — reflecting a direction off a wall is an
integer operation on its index, and the velocity it gives back is the old one with a component
negated, to the bit. `tests/golden-fresh.test.ts` reruns this script and requires the committed
file byte for byte.
"""
import math

N = 1024
Q = 1 << 14


def rnd(x: float) -> int:
    return int(math.floor(abs(x) + 0.5)) * (1 if x >= 0 else -1)


cos = [0] * N
sin = [0] * N
for i in range(0, 129):
    a = 2 * math.pi * i / N
    cos[i], sin[i] = rnd(math.cos(a) * Q), rnd(math.sin(a) * Q)
for i in range(129, 257):  # second octant: swap the axes
    cos[i], sin[i] = sin[256 - i], cos[256 - i]
for i in range(257, 513):  # second quadrant: mirror in the y axis
    cos[i], sin[i] = -cos[512 - i], sin[512 - i]
for i in range(513, N):  # lower half: mirror in the x axis
    cos[i], sin[i] = cos[N - i], -sin[N - i]


def rows(values):
    return "\n".join(
        "  " + ", ".join(str(v) for v in values[i : i + 16]) + "," for i in range(0, N, 16)
    )


print(
    f"""// GENERATED by packages/geom/golden/directions.py — do not edit; rerun it.
// tests/golden-fresh.test.ts requires this file to be exactly what the script prints.

/** cos of direction `d`, scaled by 2^14. */
export const COS: readonly number[] = [
{rows(cos)}
];

/** sin of direction `d`, scaled by 2^14. */
export const SIN: readonly number[] = [
{rows(sin)}
];"""
)
